### PR TITLE
Remove deprecation warning

### PR DESCRIPTION
**Pull request by kytrinyx**
Use the preferred method for updating implementation files.

FYI @Insti 

I'm going to merge this because it's blocking deploy.

### CODE REVIEW

**Comment by petertseng** [comment]
Hey, sorry to bother, but it looks like https://github.com/exercism/exercism.io/issues/2882 / http://tinyletter.com/exercism/letters/mutation-caching-naming-things-and-other-exercism-tidbits again. For a demonstration, if I currently look at http://x.exercism.io/v2/exercises/ruby/sieve I see that a sieve.rb is included, and it is not supposed to be, since it is not in https://github.com/exercism/xruby/tree/master/exercises/sieve (nor is it anywhere in the xruby repo according to a code search)

Now, I'm mentioning it on this PR because it **looks** (now, I could be wrong) like this is the cause, right? `merge_files` mutates (via `merge!`) the `files` hash in-place, whereas the `files = files.merge(...)` was reassigning to a new hash, so the behaviours are different.

**Comment by petertseng** [comment]
> it **looks** like this is the cause

Eh, one could argue that x-api is just doing its job and making use of the APIs available to it. I should have mentioned this on the https://github.com/exercism/trackler/pull/39 that introduced this API. Sorry about that. Will go there.

**Comment by Insti** [comment]
I will look into this today.

**Comment by Insti** [comment]
x-api should still work if this change is reverted.
(It will just log deprecation warnings)

**Pull request merged**
