### PR TITLE
Allow language-specific README inclusion at the problem level

### LINKED ISSUE #44: Allow language-specific README inclusion at the problem level
We currently have a language-specific inclusion (`SETUP.md`) that will be added to every single README in the track.

As suggested by @pminten in https://github.com/exercism/x-common/pull/67#issuecomment-89819097 we should also have the ability to include language-specific content on a problem-by-problem basis.

### PR DESCRIPTION
**Pull request by abhishekbose87**
Fixes #44

### CODE REVIEW

**Comment by abhishekbose87** [comment]
@kytrinyx I have made the relevant code changes. If it looks fine, I will go ahead and fix the tests too.

**Comment by kytrinyx** [comment]
That was quick! This looks good to me.

**Comment by abhishekbose87** [comment]
@kytrinyx I have added a newline(for content present in "HINTS.md") in the strings, expected files to get my test cases passed. Something tells me that this might become confusing in the long run. What do you think ?

**Comment by kytrinyx** [comment]
You mean confusing to have lots of empty newlines next to each other if the `HINTS.md` and `SETUP.md` files are empty?

How about making that something like:

```
def custom
  [setup, hints].compact.join("\n")
end
```

**Comment by abhishekbose87** [comment]
Yes I agree with your suggestion, but then we would have to club setup and hints together in the readme too. Currently I have {instructions} in between two for the reason that exercise hint should be placed just after the exercise_description{blurb} as it is specific to the exercise.
```
@text ||= <<-README
# #{name}

#{blurb}

#{exercise_help}
#{instructions}
#{help}
## Source

#{source} [view source](#{source_url})
README
```

**Comment by kytrinyx** [comment]
If we name the method something else, we can stick `instructions` in the array before we compact. Should be fine.

**Comment by abhishekbose87** [comment]
Hope this looks good now :smiley:

**Comment by kytrinyx** [comment]
Yeah, this looks great. I like the name `exercise_guide`.

Would you mind squashing the commits, and making sure the commit message follows Tim Pope's guidelines?

- http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request
- http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html

**Comment by abhishekbose87** [comment]
Cleaned up my commits. Thanks for the links :+1:

**Comment by kytrinyx** [comment]
Excellent, thank you!

**Comment by abhishekbose87** [comment]
:smiley:

**Pull request merged**
