### PR TITLE
Update submodules for crystal

### PR DESCRIPTION
**Pull request by mhelmetag**
@kytrinyx ,

Is this right?

I've never used submodules before...

### CODE REVIEW

**Comment by kytrinyx** [comment]
This looks right. Nice!

**Comment by kytrinyx** [comment]
Damn, not quite. Reverted. Let me get this sorted out.

**Comment by mhelmetag** [comment]
Eek... Sorry!

**Comment by kytrinyx** [comment]
It was missing the actual repository. No harm done. Fixed in master.

**Comment by mhelmetag** [comment]
Thanks a bunch!

**Comment by mhelmetag** [comment]
Do you know how you add submodules correctly? I just did `git submodule add https://github.com/exercism/xcrystal.git tracks/crystal`.

**Comment by kytrinyx** [comment]
That's how I do it. I don't know why I didn't get the actual repository when you did it, just an empty directory.

**Pull request merged**
